version: "3.8"
services:
  redis:
    image: "redis:alpine"
    expose:
      - 6379
    networks:
      - main

  worker:
    build:
      context: ./
      dockerfile: Dockerfile
    links:
      - "redis"
    env_file:
      - docker.env
    command: /bin/bash -c "npm run worker:start:prod"
    networks:
      - main

  webapp:
    build:
      context: ./
      dockerfile: Dockerfile
    profiles: ["webapp"]
    ports:
      - 3000:3000
    links:
      - "redis"
    #restart:
    #  unless-stopped
    env_file:
      - docker.env
    command: /bin/bash -c "npm run webapp:start:prod"
    networks:
      - main

networks:
  main:
    name: main
